baseurl = "https://beyondrawdata.rbind.io/"
languageCode = "en-us"
title = "B̺eyond͆ R̺aw͆ D̺ata͆"#B͆E͆Y͆O͆N͆D R͆A͆W͆ D͆A͆T͆A͆
paginate = "10" # Number of posts per page
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
theme = "Mainroad"
disqusShortname = "beyond-raw-data-blog" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-137362362-1" # Enable Google Analytics by entering your tracking id
#ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "J://Personalprojects//Blogsite//CarlvinJerry.github.io"

#[Author] # Used in authorbox
 #name = "Carlvin M"
   #pre = "<i class='fa fa-user fa-fw'></i>"
    #weight = 5
    #identifier = "about"
   # url = "/about/"
  #name = "Carlvin M"
  #bio = "Carlvin is a young data science enthusiast who loves building and testing all things data analytics and visualization. Here to learn, here to grow! Have questions or suggestions? Feel free to open an issue on GitHub or ask me on Twitter.Thanks for reading!"
  avatar = "img/avatar.png"

[menu]
 [[menu.main]]
    name = "Home"
    identifier = "home"
    url = ""
    weight = 1
	
 [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/post/"
    weight = 2
	
 [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"
	avatar = "img/avatar.png"
 
 [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 6
    url = "/contact/"
	
 [[menu.main]]
    name = "RSS Feed"
    identifier = "RSS"
    url = "/post/index.xml"
    weight = 101

[[menu.main]]
    name = "R Bloggers"
    identifier = "R"
    url = "https://www.r-bloggers.com/"
    weight = 110



[Params]
  subtitle = "Fitting a thousand stories,in a nutshell..."
  description = "Carlvin's personal blog about everything Data Science" # Site description. Used in meta description
  copyright = "Carlvin M" # copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true 
  #logoPath = "https://github.com/rbind/data-blog/blob/master/logos/datascienceblog_logo_wide_alt.png"
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  # post_meta = ["date", "categories", "translations"] # Order of post meta information. Use ["none"] to turn off completely.
  postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
  #postSections = ["blog", "news"] # alternative that shows more than one section's pages
  #dateformat = "2006-01-02" # change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  customCSS = ["css/custom.css"] # Include custom CSS files

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
 

[Params.widgets.social]
  # Enable parts of social widget
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "@Ctrl_Shft_Del"
  #gnusocial = "*" # Specify href (e.g. https://quitter.se/yourusername)
  #facebook = "*"
  googleplus = "carlvinjerry@gmail.com"
  
  # SNS career oriented
  linkedin = "*"
  
  # Techie
  github = "CarlvinJerry"
 
  
